<?php

$labels = array(
    "pluginTitle" => __("WooCommerce All-in-One discounts & gifts", "woodiscount"),
    "newDiscountButton" => __("new discount", "woodiscount"),
    "saveButton" => __("save", "woodiscount"),
    "closeButton" => __("close", "woodiscount"),
    "discountListName" => __("Discount Name", "woodiscount"),
    "discountListType" => __("Discount Type", "woodiscount"),
    "discountListDateFrom" => __("Date From", "woodiscount"),
    "discountListDateTo" => __("Date To", "woodiscount"),
    "discountListEdit" => __("Edit", "woodiscount"),
    "discountListRemove" => __("Remove", "woodiscount"),
    "discountListStatus" => __("Status", "woodiscount"),
    "editDiscountHeader" => __("Discount Editor", "woodiscount"),
    "editDiscountNameInput" => __("Discount Name", "woodiscount"),
    "editDiscountTypeInput" => __("Select Discount Type", "woodiscount"),
    "editDiscountDates" => __("Discount Dates Range", "woodiscount"),
    "productListSearchCategory" => __("Select category", "woodiscount"),
    "productListSearchTag" => __("Select tag", "woodiscount"),
    "productListSearchProduct" => __("Search product", "woodiscount"),
    "subtotalFromPlaceholder" => __("Min", "woodiscount"),
    "subtotalToPlaceholder" => __("Max", "woodiscount"),
    "commonDiscountPlaceholder" => __("Discount", "woodiscount"),
    "commonCartStringPlaceholder" => __("Discount name in Cart", "woodiscount"),
    "statusLabelActive" => __("Active", "woodiscount"),
    "statusLabelInactive" => __("Out of Dates", "woodiscount"),
    "discountNameCommon" => __("Cart Subtotal Discount", "woodiscount"),
    "discountNameProduct" => __("Product Discount", "woodiscount"),
    "discountNamePayTake" => __("Pay Less Take More", "woodiscount"),
    "discountNameGift" => __("Gift", "woodiscount"),
    "productDiscountPlaceholder" => __("Discount value, fix or %", "woodiscount"),
    "productDescriptionPlaceholder" => __("Description for Product Page", "woodiscount"),
    "productCatDescriptionPlaceholder" => __("Description for Category Page", "woodiscount"),
    "addItemToListTooltip" => __("Add to List", "woodiscount"),
    "payTakeItemsToPay" => __("Items to Pay", "woodiscount"),
    "payTakeItemsToTake" => __("Items to Take", "woodiscount"),
    "giftSubtotalPlaceholder" => __("Cart Subtotal for Gift", "woodiscount"),
    "giftListHeader" => __("Gift Products", "woodiscount"),
    "commonBlockHeader" => __("Common Settings", "woodiscount"),
    "subtotalBlockHeader" => __("Cart Subtotal Settings", "woodiscount"),
    "productListBlockHeader" => __("Product List", "woodiscount"),
    "productBlockHeader" => __("Product Discount Settings", "woodiscount"),
    "payTakeBlockHeader" => __("Pay Less Take More Discount Settings", "woodiscount"),
    "giftBlockHeader" => __("Gifts Settings", "woodiscount"),
    "removingHeader" => __("Remove Discount", "woodiscount"),
    "removingText" => __("Are you sure you want to remove this discount?", "woodiscount"),
    "infoDiscountName" => __("Name for this discount (any).", "woodiscount"),
    "infoDiscountType" => __("Select a type of discount. Common: reduce cart subtotal; Products: set sale prices for selected products; Pay Less Take More: add free products to cart (condition - customer ) ; ", "woodiscount"),
    "infoDiscountDates" => __("Dates range for discount. If dates are not selected, the discount will be active from now and forever.", "woodiscount"),
    "infoSubtotal" => __("Min and max values of cart subtotal, when the discount will be applied.", "woodiscount"),
    "infoCommonDiscount" => __("The value of discount. You can enter fix sum (e.g. '100') or percent (e.g. '10%').", "woodiscount"),
    "infoCartString" => __("The name of discount that will be shown for customer on cart page.", "woodiscount"),
    "infoProductList" => __("Select products, categories and tags for which you want to apply this discount.", "woodiscount"),
    "infoProductDescription" => __("Text that will be displayed on product page (optional).", "woodiscount"),
    "infoCatDescription" => __("Text that will be displayed on category page (optional).", "woodiscount"),
    "infoItemsPay" => __("Number of products that customer have to put in the cart for taking free products.", "woodiscount"),
    "infoItemsTake" => __("Number of products that customer will receive in fact.", "woodiscount"),
    "infoGiftProduct" => __("Select product that will be added to cart for free. It's recommended to create special products for this. Only one product can be selected for each Gift Discount."),
    "subtotalAlert" => __("Max value of cart subtotal can not be less or equal to min value.", "woodiscount"),
    "paytakeAlert" => __("Items-to-take quantity can not be less or equal to items-to-pay quantity.", "woodiscount"),
    "typeProductName" => __("Start to type product name...", "woodiscount"),
    "productListAlert" => __("Select at least 1 product for this discount'", "woodiscount"),

);

$discountTypes = array(
    [
        'id' => 'common',
        'name' => __("Common discount", "woodiscount"),
    ],
    [
        'id' => 'products',
        'name' => __("Product discount", "woodiscount"),
    ],
    [
        'id' => 'payTake',
        'name' => __("Pay Less Take More", "woodiscount"),
    ],
    [
        'id' => 'gift',
        'name' => __("Gift", "woodiscount"),
    ]
);